services:
  - type: web
    name: cms-django
    env: python
    region: singapore  # または tokyo
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn cms_django.wsgi:application
    preDeployCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrate
